### ISSUE TITLE
show ledger path not working properly

### ISSUE THREAD

**Issue by murbard** [obsidiansystems/ledger-app-tezos#26] opened 2018-09-17 20:42 UTC
Running `tezos-client show ledger path ...` shows the following error. 

`APDU level error: Unexpected sequence number (expected 0, got 191)` on the console (3 times)
and `Unrecognized operation` on the ledger.

**Comment by jdsika** [comment] 2018-09-17 20:46
I can confirm and already reported it on Reddit. But I need time to reproduce the error and deliver more details.

**Comment by jhartzell42** [comment] 2018-09-18 19:34
Could you please post the entire error, not just those portions of it?

**Comment by jhartzell42** [comment] 2018-09-18 19:35
Can you also please run it with `export TEZOS_LOG="client.signer.ledger -> debug"` first?

**Comment by jhartzell42** [comment] 2018-11-20 16:43
This has to do with U2F support. On macOS, U2F support sometimes causes things not to go through at all -- retrying until it works is the current work-around. On Linux, this warning is spurious and has been changed to reflect that.

**Comment by jhartzell42** [comment] 2018-11-20 16:43
We are working on completely getting rid of this glitch.

**Comment by 3noch** [comment] 2019-01-15 20:59
This is a duplicate of #30. Please refer there for more details and how to resolve.

**Closed by 3noch** 2019-01-15 20:59 UTC
